CREATE SEQUENCE account_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE account ALTER COLUMN id SET DEFAULT nextval('account_id_seq');

CREATE SEQUENCE equipment_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE equipment ALTER COLUMN id SET DEFAULT nextval('equipment_id_seq');

CREATE SEQUENCE exercise_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE exercise ALTER COLUMN id SET DEFAULT nextval('exercise_id_seq');

CREATE SEQUENCE plan_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE plan ALTER COLUMN id SET DEFAULT nextval('plan_id_seq');

CREATE SEQUENCE description_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE description ALTER COLUMN id SET DEFAULT nextval('description_id_seq');

CREATE SEQUENCE phase_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE phase ALTER COLUMN id SET DEFAULT nextval('phase_id_seq');

CREATE SEQUENCE workout_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE workout ALTER COLUMN id SET DEFAULT nextval('workout_id_seq');

CREATE SEQUENCE execution_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE execution ALTER COLUMN id SET DEFAULT nextval('execution_id_seq');

CREATE SEQUENCE user_workout_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE user_workout ALTER COLUMN id SET DEFAULT nextval('user_workout_id_seq');

CREATE SEQUENCE account_record_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE account_record ALTER COLUMN id SET DEFAULT nextval('account_record_id_seq');

CREATE SEQUENCE role_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE role ALTER COLUMN id SET DEFAULT nextval('role_id_seq');