INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (69, 6, '2013-05-10 00:00:00', 1, 3, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (25, 11, '2013-06-07 00:00:00', 1, 5, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (30, 8, '2013-05-31 00:00:00', 1, 4, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (71, 10, '2013-05-10 00:00:00', 1, 5, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (68, 4, '2013-05-10 00:00:00', 1, 2, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (22, 4, '2013-06-07 00:00:00', 1, 2, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (23, 6, '2013-06-07 00:00:00', 1, 3, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (24, 8, '2013-06-07 00:00:00', 1, 4, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (67, 3, '2013-05-10 00:00:00', 1, 1, '12;12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (38, 12, '2013-06-05 00:00:00', 1, 2, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (39, 13, '2013-06-05 00:00:00', 1, 3, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (40, 14, '2013-06-05 00:00:00', 1, 4, '60;60;60', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (98, 17, '2013-05-06 00:00:00', 1, 2, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (45, 15, '2013-06-02 00:00:00', 1, 4, '55;55;55', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (83, 22, '2013-05-05 00:00:00', 1, 2, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (86, 24, '2013-05-05 00:00:00', 1, 5, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (59, 23, '2013-05-26 00:00:00', 1, 3, '12;12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (36, 15, '2013-05-29 00:00:00', 1, 5, '50;50;50', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (44, 23, '2013-06-02 00:00:00', 1, 3, '12;12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (52, 16, '2013-05-27 00:00:00', 1, 1, '12;12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (99, 18, '2013-05-06 00:00:00', 1, 3, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (50, 19, '2013-06-03 00:00:00', 1, 4, '12;12;15', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (82, 21, '2013-05-05 00:00:00', 1, 1, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (47, 16, '2013-06-03 00:00:00', 1, 1, '12;12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (48, 17, '2013-06-03 00:00:00', 1, 2, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (49, 18, '2013-06-03 00:00:00', 1, 3, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (51, 20, '2013-06-03 00:00:00', 1, 5, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (42, 21, '2013-06-02 00:00:00', 1, 1, '12;12;10', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (43, 22, '2013-06-02 00:00:00', 1, 2, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (94, 23, '2013-05-19 00:00:00', 1, 3, '12;12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (46, 24, '2013-06-02 00:00:00', 1, 5, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (63, 4, '2013-05-03 00:00:00', 1, 2, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (64, 6, '2013-05-03 00:00:00', 1, 3, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (66, 10, '2013-05-03 00:00:00', 1, 5, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (37, 2, '2013-06-05 00:00:00', 1, 1, '12;12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (72, 3, '2013-05-17 00:00:00', 1, 1, '12;12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (73, 4, '2013-05-17 00:00:00', 1, 2, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (74, 6, '2013-05-17 00:00:00', 1, 3, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (76, 10, '2013-05-17 00:00:00', 1, 5, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (77, 3, '2013-05-24 00:00:00', 1, 1, '12;12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (78, 4, '2013-05-24 00:00:00', 1, 2, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (79, 6, '2013-05-24 00:00:00', 1, 3, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (81, 10, '2013-05-24 00:00:00', 1, 5, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (27, 3, '2013-05-31 00:00:00', 1, 1, '12;12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (28, 4, '2013-05-31 00:00:00', 1, 2, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (29, 6, '2013-05-31 00:00:00', 1, 3, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (31, 10, '2013-05-31 00:00:00', 1, 5, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (87, 21, '2013-05-12 00:00:00', 1, 1, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (88, 22, '2013-05-12 00:00:00', 1, 2, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (41, 15, '2013-06-05 00:00:00', 1, 5, '60;60;60', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (91, 24, '2013-05-12 00:00:00', 1, 5, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (92, 21, '2013-05-19 00:00:00', 1, 1, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (93, 22, '2013-05-19 00:00:00', 1, 2, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (84, 23, '2013-05-05 00:00:00', 1, 3, '12;12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (96, 24, '2013-05-19 00:00:00', 1, 5, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (57, 21, '2013-05-26 00:00:00', 1, 1, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (58, 22, '2013-05-26 00:00:00', 1, 2, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (89, 23, '2013-05-12 00:00:00', 1, 3, '12;12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (61, 24, '2013-05-26 00:00:00', 1, 5, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (97, 16, '2013-05-06 00:00:00', 1, 1, '12;12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (53, 17, '2013-05-27 00:00:00', 1, 2, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (54, 18, '2013-05-27 00:00:00', 1, 3, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (56, 20, '2013-05-27 00:00:00', 1, 5, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (35, 14, '2013-05-29 00:00:00', 1, 4, '60;60;60', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (32, 2, '2013-05-29 00:00:00', 1, 1, '12;12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (33, 12, '2013-05-29 00:00:00', 1, 2, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (34, 13, '2013-05-29 00:00:00', 1, 3, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (62, 3, '2013-05-03 00:00:00', 1, 1, '12;12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (21, 3, '2013-06-07 00:00:00', 1, 1, '12;12;10;10', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (60, 15, '2013-05-26 00:00:00', 1, 4, '45;45;45', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (95, 15, '2013-05-19 00:00:00', 1, 4, '35;35;35', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (90, 15, '2013-05-12 00:00:00', 1, 4, '25;25;25', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (85, 15, '2013-05-05 00:00:00', 1, 4, '20;20;20', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (65, 8, '2013-05-03 00:00:00', 1, 4, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (70, 8, '2013-05-10 00:00:00', 1, 4, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (75, 8, '2013-05-17 00:00:00', 1, 4, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (80, 8, '2013-05-24 00:00:00', 1, 4, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (55, 19, '2013-05-27 00:00:00', 1, 4, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (1, 3, '2014-03-28 00:00:00', 1, 1, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (2, 4, '2014-03-28 00:00:00', 1, 2, '12;12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (3, 96, '2014-03-28 00:00:00', 1, 3, '12;12;13', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (4, 90, '2014-03-28 00:00:00', 1, 4, '6;6;6', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (5, 36, '2014-03-28 00:00:00', 1, 5, '12;12;12', NULL, true);
INSERT INTO day_exercises (id, type, date, calendar, "position", series, series_array, confirmed) VALUES (6, 35, '2014-03-28 00:00:00', 1, 6, '12;12;16', NULL, true);

INSERT INTO exercise_bars (id, equipment, exercise) VALUES (48, 1, 4);

INSERT INTO exercise_benches (id, exercise, equipment) VALUES (11, 25, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (12, 65, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (13, 66, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (14, 70, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (15, 71, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (16, 75, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (17, 76, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (18, 80, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (19, 81, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (20, 45, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (21, 46, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (22, 60, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (23, 61, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (24, 85, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (25, 86, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (26, 91, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (27, 90, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (28, 95, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (29, 96, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (42, 32, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (43, 33, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (44, 34, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (45, 36, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (46, 37, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (47, 38, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (48, 39, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (49, 41, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (338, 3, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (339, 5, 1);
INSERT INTO exercise_benches (id, exercise, equipment) VALUES (340, 6, 1);

INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (13, 31, 1);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (14, 66, 2);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (15, 71, 1);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (16, 76, 1);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (17, 81, 1);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (18, 44, 1);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (19, 44, 2);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (20, 59, 1);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (21, 59, 2);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (22, 84, 1);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (23, 84, 2);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (24, 89, 1);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (25, 89, 2);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (26, 94, 1);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (27, 94, 2);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (34, 33, 1);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (35, 33, 2);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (36, 38, 1);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (37, 38, 2);
INSERT INTO exercise_dumbbells (id, exercise, equipment) VALUES (384, 6, 2);

INSERT INTO exercise_loads (id, exercise, equipment) VALUES (54, 21, 12);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (56, 21, 13);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (57, 21, 10);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (58, 21, 11);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (59, 22, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (60, 22, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (61, 22, 12);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (62, 22, 13);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (63, 23, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (64, 23, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (65, 24, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (66, 24, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (67, 24, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (68, 24, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (69, 24, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (70, 24, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (73, 25, 12);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (74, 25, 13);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (75, 27, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (76, 27, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (77, 27, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (78, 27, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (79, 27, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (80, 27, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (81, 28, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (82, 28, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (83, 28, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (84, 28, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (85, 28, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (86, 28, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (87, 28, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (88, 28, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (89, 29, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (90, 29, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (91, 29, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (92, 29, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (93, 29, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (94, 29, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (95, 30, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (96, 30, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (97, 30, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (98, 30, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (99, 30, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (100, 30, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (101, 31, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (102, 31, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (103, 31, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (104, 62, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (105, 62, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (106, 62, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (107, 62, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (108, 63, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (109, 63, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (110, 64, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (111, 64, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (112, 65, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (113, 65, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (114, 66, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (115, 66, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (116, 67, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (117, 67, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (118, 68, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (119, 68, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (120, 68, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (121, 68, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (122, 69, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (123, 69, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (124, 69, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (125, 69, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (126, 70, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (127, 70, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (128, 70, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (129, 70, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (130, 71, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (131, 71, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (132, 72, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (133, 72, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (134, 72, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (135, 72, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (136, 73, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (137, 73, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (138, 73, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (139, 73, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (140, 73, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (141, 73, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (142, 74, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (143, 74, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (144, 74, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (145, 74, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (146, 75, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (147, 75, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (148, 75, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (149, 75, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (150, 76, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (151, 76, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (152, 76, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (153, 77, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (154, 77, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (155, 77, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (156, 77, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (157, 78, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (158, 78, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (159, 78, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (160, 78, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (161, 78, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (162, 78, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (163, 79, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (164, 79, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (165, 79, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (166, 79, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (167, 80, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (168, 80, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (169, 80, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (170, 80, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (171, 81, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (172, 81, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (173, 81, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (175, 42, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (176, 42, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (177, 42, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (178, 42, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (179, 43, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (180, 43, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (181, 43, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (182, 43, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (183, 44, 11);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (184, 44, 10);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (185, 44, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (186, 44, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (187, 44, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (188, 44, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (189, 44, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (190, 44, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (191, 44, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (192, 44, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (193, 46, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (194, 46, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (195, 57, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (196, 57, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (197, 57, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (198, 57, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (199, 58, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (200, 58, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (201, 59, 11);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (202, 59, 10);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (203, 59, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (204, 59, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (205, 59, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (206, 59, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (207, 59, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (208, 59, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (209, 59, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (210, 59, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (211, 61, 10);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (212, 61, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (213, 61, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (214, 61, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (215, 61, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (216, 61, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (217, 82, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (218, 82, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (219, 82, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (220, 82, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (221, 83, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (222, 83, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (223, 83, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (224, 83, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (225, 84, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (226, 84, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (227, 84, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (228, 84, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (229, 86, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (230, 86, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (231, 87, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (232, 87, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (233, 88, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (234, 88, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (235, 88, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (236, 88, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (237, 89, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (238, 89, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (239, 89, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (240, 89, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (241, 89, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (242, 89, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (243, 91, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (244, 91, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (245, 92, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (246, 92, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (247, 92, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (248, 92, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (249, 93, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (250, 93, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (251, 93, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (252, 93, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (253, 93, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (254, 93, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (255, 94, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (256, 94, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (257, 94, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (258, 94, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (259, 94, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (260, 94, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (261, 96, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (262, 96, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (263, 96, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (264, 96, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (265, 97, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (266, 97, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (267, 97, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (268, 97, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (269, 98, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (270, 99, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (271, 99, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (272, 99, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (273, 99, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (320, 52, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (321, 52, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (322, 52, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (323, 52, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (324, 52, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (325, 52, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (326, 53, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (327, 54, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (328, 54, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (329, 54, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (330, 54, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (331, 54, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (332, 54, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (333, 54, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (334, 54, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (335, 55, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (336, 55, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (337, 55, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (338, 55, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (339, 56, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (340, 56, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (341, 47, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (342, 47, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (343, 47, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (344, 47, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (345, 48, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (346, 49, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (347, 49, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (348, 49, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (349, 49, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (350, 49, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (351, 49, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (352, 49, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (353, 49, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (354, 49, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (355, 49, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (356, 50, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (357, 50, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (358, 50, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (359, 50, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (360, 51, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (361, 51, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (442, 32, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (443, 32, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (444, 32, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (445, 32, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (446, 32, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (447, 32, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (448, 32, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (449, 32, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (450, 32, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (451, 32, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (452, 33, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (453, 33, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (454, 33, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (455, 33, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (456, 33, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (457, 33, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (458, 34, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (459, 34, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (460, 34, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (461, 34, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (462, 34, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (463, 34, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (464, 35, 9);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (465, 35, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (466, 35, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (467, 35, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (468, 35, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (469, 35, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (470, 35, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (471, 35, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (472, 35, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (473, 35, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (478, 37, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (479, 37, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (482, 38, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (483, 38, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (484, 38, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (485, 38, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (486, 38, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (487, 38, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (492, 40, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (493, 40, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (494, 40, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (495, 40, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (496, 40, 12);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (497, 40, 13);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (498, 37, 12);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (499, 37, 13);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (500, 39, 12);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (501, 39, 13);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4850, 1, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4851, 1, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4852, 1, 12);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4853, 1, 13);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4854, 2, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4855, 2, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4856, 2, 3);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4857, 2, 4);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4858, 2, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4859, 2, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4860, 2, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4861, 2, 12);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4862, 2, 13);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4863, 2, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4864, 3, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4865, 3, 12);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4866, 3, 13);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4867, 5, 1);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4868, 5, 2);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4869, 5, 5);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4870, 5, 15);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4871, 6, 6);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4872, 6, 7);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4873, 6, 8);
INSERT INTO exercise_loads (id, exercise, equipment) VALUES (4874, 6, 9);

INSERT INTO exercise_necks (id, exercise, equipment) VALUES (16, 21, 2);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (17, 22, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (18, 23, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (19, 24, 2);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (20, 25, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (21, 27, 2);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (22, 28, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (23, 29, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (24, 30, 2);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (25, 62, 2);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (26, 63, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (27, 64, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (28, 65, 2);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (29, 67, 2);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (30, 68, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (31, 69, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (32, 70, 2);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (33, 72, 2);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (34, 73, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (35, 74, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (36, 75, 2);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (37, 77, 2);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (38, 78, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (39, 79, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (40, 80, 2);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (41, 42, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (42, 43, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (43, 46, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (44, 57, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (45, 58, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (46, 61, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (47, 82, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (48, 83, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (49, 86, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (50, 87, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (51, 88, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (52, 91, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (53, 92, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (54, 93, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (55, 96, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (56, 97, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (57, 99, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (68, 52, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (69, 54, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (70, 55, 2);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (71, 56, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (72, 47, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (73, 49, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (74, 50, 2);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (75, 51, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (85, 32, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (86, 34, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (87, 35, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (88, 37, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (89, 39, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (90, 40, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (618, 1, 2);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (619, 2, 1);
INSERT INTO exercise_necks (id, exercise, equipment) VALUES (620, 5, 2);

INSERT INTO exercise_stands (id, exercise, equipment) VALUES (23, 25, 1);
INSERT INTO exercise_stands (id, exercise, equipment) VALUES (24, 25, 2);
INSERT INTO exercise_stands (id, exercise, equipment) VALUES (25, 98, 1);
INSERT INTO exercise_stands (id, exercise, equipment) VALUES (26, 98, 2);
INSERT INTO exercise_stands (id, exercise, equipment) VALUES (31, 53, 1);
INSERT INTO exercise_stands (id, exercise, equipment) VALUES (32, 53, 2);
INSERT INTO exercise_stands (id, exercise, equipment) VALUES (33, 48, 1);
INSERT INTO exercise_stands (id, exercise, equipment) VALUES (34, 48, 2);
INSERT INTO exercise_stands (id, exercise, equipment) VALUES (47, 32, 1);
INSERT INTO exercise_stands (id, exercise, equipment) VALUES (48, 32, 2);
INSERT INTO exercise_stands (id, exercise, equipment) VALUES (49, 34, 1);
INSERT INTO exercise_stands (id, exercise, equipment) VALUES (50, 34, 2);
INSERT INTO exercise_stands (id, exercise, equipment) VALUES (51, 37, 1);
INSERT INTO exercise_stands (id, exercise, equipment) VALUES (52, 37, 2);
INSERT INTO exercise_stands (id, exercise, equipment) VALUES (53, 39, 1);
INSERT INTO exercise_stands (id, exercise, equipment) VALUES (54, 39, 2);